# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/taras/OneDrive/skolenProjekt/3UgersProjektJan2017/ZYBO-master/tests/ZYBO_Master.xdc

# Block Designs: bd/hdmi_in/hdmi_in.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in || ORIG_REF_NAME==hdmi_in}]

# IP: bd/hdmi_in/ip/hdmi_in_axi_dynclk_0_0/hdmi_in_axi_dynclk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_axi_dynclk_0_0 || ORIG_REF_NAME==hdmi_in_axi_dynclk_0_0}]

# IP: bd/hdmi_in/ip/hdmi_in_axi_gpio_btn_0/hdmi_in_axi_gpio_btn_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_axi_gpio_btn_0 || ORIG_REF_NAME==hdmi_in_axi_gpio_btn_0}]

# IP: bd/hdmi_in/ip/hdmi_in_axi_gpio_led_0/hdmi_in_axi_gpio_led_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_axi_gpio_led_0 || ORIG_REF_NAME==hdmi_in_axi_gpio_led_0}]

# IP: bd/hdmi_in/ip/hdmi_in_axi_gpio_sw_0/hdmi_in_axi_gpio_sw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_axi_gpio_sw_0 || ORIG_REF_NAME==hdmi_in_axi_gpio_sw_0}]

# IP: bd/hdmi_in/ip/hdmi_in_axi_gpio_video_0/hdmi_in_axi_gpio_video_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_axi_gpio_video_0 || ORIG_REF_NAME==hdmi_in_axi_gpio_video_0}]

# IP: bd/hdmi_in/ip/hdmi_in_axi_mem_intercon_0/hdmi_in_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_axi_mem_intercon_0 || ORIG_REF_NAME==hdmi_in_axi_mem_intercon_0}]

# IP: bd/hdmi_in/ip/hdmi_in_xbar_0/hdmi_in_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_xbar_0 || ORIG_REF_NAME==hdmi_in_xbar_0}]

# IP: bd/hdmi_in/ip/hdmi_in_axi_vdma_0_0/hdmi_in_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_axi_vdma_0_0 || ORIG_REF_NAME==hdmi_in_axi_vdma_0_0}]

# IP: bd/hdmi_in/ip/hdmi_in_dvi2rgb_0_0/hdmi_in_dvi2rgb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_dvi2rgb_0_0 || ORIG_REF_NAME==hdmi_in_dvi2rgb_0_0}]

# IP: bd/hdmi_in/ip/hdmi_in_proc_sys_reset_0_0/hdmi_in_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_proc_sys_reset_0_0 || ORIG_REF_NAME==hdmi_in_proc_sys_reset_0_0}]

# IP: bd/hdmi_in/ip/hdmi_in_processing_system7_0_0/hdmi_in_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_processing_system7_0_0 || ORIG_REF_NAME==hdmi_in_processing_system7_0_0}]

# IP: bd/hdmi_in/ip/hdmi_in_processing_system7_0_axi_periph_0/hdmi_in_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==hdmi_in_processing_system7_0_axi_periph_0}]

# IP: bd/hdmi_in/ip/hdmi_in_xbar_1/hdmi_in_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_xbar_1 || ORIG_REF_NAME==hdmi_in_xbar_1}]

# IP: bd/hdmi_in/ip/hdmi_in_rgb2vga_0_0/hdmi_in_rgb2vga_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_rgb2vga_0_0 || ORIG_REF_NAME==hdmi_in_rgb2vga_0_0}]

# IP: bd/hdmi_in/ip/hdmi_in_rst_processing_system7_0_100M_0/hdmi_in_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==hdmi_in_rst_processing_system7_0_100M_0}]

# IP: bd/hdmi_in/ip/hdmi_in_rst_processing_system7_0_150M_0/hdmi_in_rst_processing_system7_0_150M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_rst_processing_system7_0_150M_0 || ORIG_REF_NAME==hdmi_in_rst_processing_system7_0_150M_0}]

# IP: bd/hdmi_in/ip/hdmi_in_v_axi4s_vid_out_0_0/hdmi_in_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==hdmi_in_v_axi4s_vid_out_0_0}]

# IP: bd/hdmi_in/ip/hdmi_in_v_tc_0_0/hdmi_in_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_v_tc_0_0 || ORIG_REF_NAME==hdmi_in_v_tc_0_0}]

# IP: bd/hdmi_in/ip/hdmi_in_v_tc_1_0/hdmi_in_v_tc_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_v_tc_1_0 || ORIG_REF_NAME==hdmi_in_v_tc_1_0}]

# IP: bd/hdmi_in/ip/hdmi_in_v_vid_in_axi4s_0_0/hdmi_in_v_vid_in_axi4s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==hdmi_in_v_vid_in_axi4s_0_0}]

# IP: bd/hdmi_in/ip/hdmi_in_xlconcat_0_0/hdmi_in_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_xlconcat_0_0 || ORIG_REF_NAME==hdmi_in_xlconcat_0_0}]

# IP: bd/hdmi_in/ip/hdmi_in_xlconstant_0_0/hdmi_in_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_xlconstant_0_0 || ORIG_REF_NAME==hdmi_in_xlconstant_0_0}]

# IP: bd/hdmi_in/ip/hdmi_in_axi_gpio_0_0/hdmi_in_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_axi_gpio_0_0 || ORIG_REF_NAME==hdmi_in_axi_gpio_0_0}]

# IP: bd/hdmi_in/ip/hdmi_in_axi_gpio_1_0/hdmi_in_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_axi_gpio_1_0 || ORIG_REF_NAME==hdmi_in_axi_gpio_1_0}]

# IP: bd/hdmi_in/ip/hdmi_in_axi_quad_spi_0_0/hdmi_in_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_axi_quad_spi_0_0 || ORIG_REF_NAME==hdmi_in_axi_quad_spi_0_0}]

# IP: bd/hdmi_in/ip/hdmi_in_s00_regslice_0/hdmi_in_s00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_s00_regslice_0 || ORIG_REF_NAME==hdmi_in_s00_regslice_0}]

# IP: bd/hdmi_in/ip/hdmi_in_s01_regslice_0/hdmi_in_s01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_s01_regslice_0 || ORIG_REF_NAME==hdmi_in_s01_regslice_0}]

# IP: bd/hdmi_in/ip/hdmi_in_m00_data_fifo_0/hdmi_in_m00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_m00_data_fifo_0 || ORIG_REF_NAME==hdmi_in_m00_data_fifo_0}]

# IP: bd/hdmi_in/ip/hdmi_in_m00_regslice_0/hdmi_in_m00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_m00_regslice_0 || ORIG_REF_NAME==hdmi_in_m00_regslice_0}]

# IP: bd/hdmi_in/ip/hdmi_in_auto_pc_0/hdmi_in_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_auto_pc_0 || ORIG_REF_NAME==hdmi_in_auto_pc_0}]

# IP: bd/hdmi_in/ip/hdmi_in_auto_us_df_0/hdmi_in_auto_us_df_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_auto_us_df_0 || ORIG_REF_NAME==hdmi_in_auto_us_df_0}]

# IP: bd/hdmi_in/ip/hdmi_in_auto_us_df_1/hdmi_in_auto_us_df_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_auto_us_df_1 || ORIG_REF_NAME==hdmi_in_auto_us_df_1}]

# IP: bd/hdmi_in/ip/hdmi_in_auto_pc_1/hdmi_in_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_auto_pc_1 || ORIG_REF_NAME==hdmi_in_auto_pc_1}]

# IP: bd/hdmi_in/ip/hdmi_in_auto_pc_2/hdmi_in_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_auto_pc_2 || ORIG_REF_NAME==hdmi_in_auto_pc_2}]

# IP: bd/hdmi_in/ip/hdmi_in_auto_pc_3/hdmi_in_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_auto_pc_3 || ORIG_REF_NAME==hdmi_in_auto_pc_3}]

# IP: bd/hdmi_in/ip/hdmi_in_auto_pc_4/hdmi_in_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_auto_pc_4 || ORIG_REF_NAME==hdmi_in_auto_pc_4}]

# IP: bd/hdmi_in/ip/hdmi_in_auto_pc_5/hdmi_in_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_auto_pc_5 || ORIG_REF_NAME==hdmi_in_auto_pc_5}]

# IP: bd/hdmi_in/ip/hdmi_in_auto_pc_6/hdmi_in_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_auto_pc_6 || ORIG_REF_NAME==hdmi_in_auto_pc_6}]

# IP: bd/hdmi_in/ip/hdmi_in_auto_pc_7/hdmi_in_auto_pc_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_auto_pc_7 || ORIG_REF_NAME==hdmi_in_auto_pc_7}]

# IP: bd/hdmi_in/ip/hdmi_in_auto_pc_8/hdmi_in_auto_pc_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_auto_pc_8 || ORIG_REF_NAME==hdmi_in_auto_pc_8}]

# IP: bd/hdmi_in/ip/hdmi_in_auto_pc_9/hdmi_in_auto_pc_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_auto_pc_9 || ORIG_REF_NAME==hdmi_in_auto_pc_9}]

# IP: bd/hdmi_in/ip/hdmi_in_auto_pc_10/hdmi_in_auto_pc_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_auto_pc_10 || ORIG_REF_NAME==hdmi_in_auto_pc_10}]

# IP: bd/hdmi_in/ip/hdmi_in_auto_pc_11/hdmi_in_auto_pc_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_auto_pc_11 || ORIG_REF_NAME==hdmi_in_auto_pc_11}]

# XDC: bd/hdmi_in/ip/hdmi_in_axi_gpio_btn_0/hdmi_in_axi_gpio_btn_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_axi_gpio_btn_0 || ORIG_REF_NAME==hdmi_in_axi_gpio_btn_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_in/ip/hdmi_in_axi_gpio_btn_0/hdmi_in_axi_gpio_btn_0_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_axi_gpio_btn_0/hdmi_in_axi_gpio_btn_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_axi_gpio_btn_0 || ORIG_REF_NAME==hdmi_in_axi_gpio_btn_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_in/ip/hdmi_in_axi_gpio_led_0/hdmi_in_axi_gpio_led_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_axi_gpio_led_0 || ORIG_REF_NAME==hdmi_in_axi_gpio_led_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_in/ip/hdmi_in_axi_gpio_led_0/hdmi_in_axi_gpio_led_0_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_axi_gpio_led_0/hdmi_in_axi_gpio_led_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_axi_gpio_led_0 || ORIG_REF_NAME==hdmi_in_axi_gpio_led_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_in/ip/hdmi_in_axi_gpio_sw_0/hdmi_in_axi_gpio_sw_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_axi_gpio_sw_0 || ORIG_REF_NAME==hdmi_in_axi_gpio_sw_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_in/ip/hdmi_in_axi_gpio_sw_0/hdmi_in_axi_gpio_sw_0_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_axi_gpio_sw_0/hdmi_in_axi_gpio_sw_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_axi_gpio_sw_0 || ORIG_REF_NAME==hdmi_in_axi_gpio_sw_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_in/ip/hdmi_in_axi_gpio_video_0/hdmi_in_axi_gpio_video_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_axi_gpio_video_0 || ORIG_REF_NAME==hdmi_in_axi_gpio_video_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_in/ip/hdmi_in_axi_gpio_video_0/hdmi_in_axi_gpio_video_0_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_axi_gpio_video_0/hdmi_in_axi_gpio_video_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_axi_gpio_video_0 || ORIG_REF_NAME==hdmi_in_axi_gpio_video_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_in/ip/hdmi_in_xbar_0/hdmi_in_xbar_0_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_axi_vdma_0_0/hdmi_in_axi_vdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_axi_vdma_0_0 || ORIG_REF_NAME==hdmi_in_axi_vdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_in/ip/hdmi_in_axi_vdma_0_0/hdmi_in_axi_vdma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_axi_vdma_0_0 || ORIG_REF_NAME==hdmi_in_axi_vdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_in/ip/hdmi_in_axi_vdma_0_0/hdmi_in_axi_vdma_0_0_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_dvi2rgb_0_0/src/dvi2rgb.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_dvi2rgb_0_0 || ORIG_REF_NAME==hdmi_in_dvi2rgb_0_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_in/ip/hdmi_in_dvi2rgb_0_0/src/dvi2rgb_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_proc_sys_reset_0_0/hdmi_in_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_proc_sys_reset_0_0 || ORIG_REF_NAME==hdmi_in_proc_sys_reset_0_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_in/ip/hdmi_in_proc_sys_reset_0_0/hdmi_in_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_proc_sys_reset_0_0 || ORIG_REF_NAME==hdmi_in_proc_sys_reset_0_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_in/ip/hdmi_in_proc_sys_reset_0_0/hdmi_in_proc_sys_reset_0_0_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_processing_system7_0_0/hdmi_in_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_processing_system7_0_0 || ORIG_REF_NAME==hdmi_in_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/hdmi_in/ip/hdmi_in_xbar_1/hdmi_in_xbar_1_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_rst_processing_system7_0_100M_0/hdmi_in_rst_processing_system7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==hdmi_in_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_in/ip/hdmi_in_rst_processing_system7_0_100M_0/hdmi_in_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==hdmi_in_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_in/ip/hdmi_in_rst_processing_system7_0_100M_0/hdmi_in_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_rst_processing_system7_0_150M_0/hdmi_in_rst_processing_system7_0_150M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_rst_processing_system7_0_150M_0 || ORIG_REF_NAME==hdmi_in_rst_processing_system7_0_150M_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_in/ip/hdmi_in_rst_processing_system7_0_150M_0/hdmi_in_rst_processing_system7_0_150M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_rst_processing_system7_0_150M_0 || ORIG_REF_NAME==hdmi_in_rst_processing_system7_0_150M_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_in/ip/hdmi_in_rst_processing_system7_0_150M_0/hdmi_in_rst_processing_system7_0_150M_0_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_v_axi4s_vid_out_0_0/hdmi_in_v_axi4s_vid_out_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==hdmi_in_v_axi4s_vid_out_0_0}] {/inst }]/inst ]]

# XDC: bd/hdmi_in/ip/hdmi_in_v_axi4s_vid_out_0_0/hdmi_in_v_axi4s_vid_out_0_0_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_v_tc_0_0/hdmi_in_v_tc_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_v_tc_0_0 || ORIG_REF_NAME==hdmi_in_v_tc_0_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_in/ip/hdmi_in_v_tc_0_0/hdmi_in_v_tc_0_0_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_v_tc_1_0/hdmi_in_v_tc_1_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_v_tc_1_0 || ORIG_REF_NAME==hdmi_in_v_tc_1_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_in/ip/hdmi_in_v_tc_1_0/hdmi_in_v_tc_1_0_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_v_vid_in_axi4s_0_0/hdmi_in_v_vid_in_axi4s_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==hdmi_in_v_vid_in_axi4s_0_0}] {/inst }]/inst ]]

# XDC: bd/hdmi_in/ip/hdmi_in_v_vid_in_axi4s_0_0/hdmi_in_v_vid_in_axi4s_0_0_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_axi_gpio_0_0/hdmi_in_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_axi_gpio_0_0 || ORIG_REF_NAME==hdmi_in_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_in/ip/hdmi_in_axi_gpio_0_0/hdmi_in_axi_gpio_0_0_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_axi_gpio_0_0/hdmi_in_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_axi_gpio_0_0 || ORIG_REF_NAME==hdmi_in_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_in/ip/hdmi_in_axi_gpio_1_0/hdmi_in_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_axi_gpio_1_0 || ORIG_REF_NAME==hdmi_in_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_in/ip/hdmi_in_axi_gpio_1_0/hdmi_in_axi_gpio_1_0_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_axi_gpio_1_0/hdmi_in_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_axi_gpio_1_0 || ORIG_REF_NAME==hdmi_in_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_in/ip/hdmi_in_axi_quad_spi_0_0/hdmi_in_axi_quad_spi_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_axi_quad_spi_0_0 || ORIG_REF_NAME==hdmi_in_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_in/ip/hdmi_in_axi_quad_spi_0_0/hdmi_in_axi_quad_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_axi_quad_spi_0_0 || ORIG_REF_NAME==hdmi_in_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_in/ip/hdmi_in_axi_quad_spi_0_0/hdmi_in_axi_quad_spi_0_0_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_axi_quad_spi_0_0/hdmi_in_axi_quad_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_axi_quad_spi_0_0 || ORIG_REF_NAME==hdmi_in_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_in/ip/hdmi_in_s00_regslice_0/hdmi_in_s00_regslice_0_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_s01_regslice_0/hdmi_in_s01_regslice_0_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_m00_data_fifo_0/hdmi_in_m00_data_fifo_0_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_m00_regslice_0/hdmi_in_m00_regslice_0_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_auto_pc_0/hdmi_in_auto_pc_0_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_auto_us_df_0/hdmi_in_auto_us_df_0_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_auto_us_df_0/hdmi_in_auto_us_df_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_auto_us_df_0 || ORIG_REF_NAME==hdmi_in_auto_us_df_0}] {/inst }]/inst ]]

# XDC: bd/hdmi_in/ip/hdmi_in_auto_us_df_1/hdmi_in_auto_us_df_1_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_auto_us_df_1/hdmi_in_auto_us_df_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_auto_us_df_1 || ORIG_REF_NAME==hdmi_in_auto_us_df_1}] {/inst }]/inst ]]

# XDC: bd/hdmi_in/ip/hdmi_in_auto_pc_1/hdmi_in_auto_pc_1_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_auto_pc_2/hdmi_in_auto_pc_2_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_auto_pc_3/hdmi_in_auto_pc_3_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_auto_pc_4/hdmi_in_auto_pc_4_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_auto_pc_5/hdmi_in_auto_pc_5_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_auto_pc_6/hdmi_in_auto_pc_6_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_auto_pc_7/hdmi_in_auto_pc_7_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_auto_pc_8/hdmi_in_auto_pc_8_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_auto_pc_9/hdmi_in_auto_pc_9_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_auto_pc_10/hdmi_in_auto_pc_10_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_auto_pc_11/hdmi_in_auto_pc_11_ooc.xdc

# XDC: bd/hdmi_in/hdmi_in_ooc.xdc
