# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Projects/jan2017/ZYBO_Master.xdc

# Block Designs: bd/design_1band/design_1band.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1band || ORIG_REF_NAME==design_1band}]

# IP: bd/design_1band/ip/design_1band_processing_system7_0_0/design_1band_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1band_processing_system7_0_0 || ORIG_REF_NAME==design_1band_processing_system7_0_0}]

# IP: bd/design_1band/ip/design_1band_axi_gpio_0_0/design_1band_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1band_axi_gpio_0_0 || ORIG_REF_NAME==design_1band_axi_gpio_0_0}]

# IP: bd/design_1band/ip/design_1band_ps7_0_axi_periph_0/design_1band_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1band_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_1band_ps7_0_axi_periph_0}]

# IP: bd/design_1band/ip/design_1band_rst_ps7_0_100M_0/design_1band_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1band_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_1band_rst_ps7_0_100M_0}]

# IP: bd/design_1band/ip/design_1band_auto_pc_0/design_1band_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1band_auto_pc_0 || ORIG_REF_NAME==design_1band_auto_pc_0}]

# XDC: bd/design_1band/design_1band_ooc.xdc
